server:
  port: 8081

spring:
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
db:
  insurance:
    jdbcUrl: "jdbc:postgresql://localhost:5432/insurance"
    username: "admin"
    password: "PWD"